In [1]:
import torch
import torch.nn as nn
import numpy as np

### Tensor

In [2]:
# default float
f1 = torch.Tensor([1])
print(f1.dtype)

torch.float32


In [3]:
a = torch.ones((3,4))
a.mean(1).shape

torch.Size([3])

In [7]:
a.sum(1,keepdim=True).shape

torch.Size([3, 1])

In [59]:
a[0,0]=0

In [60]:
a/a.sum(1).unsqueeze(1)

tensor([[0.0000, 0.3333, 0.3333, 0.3333],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])

In [43]:
# convert to long
l1 = torch.Tensor([1]).long()
print(l1.dtype)

torch.int64


In [12]:
a=torch.ones(2,3,4)
b=torch.ones(2,1,3)
torch.bmm(b,a).shape

torch.Size([2, 1, 4])

In [15]:
torch.ones(3,4)*torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# convert from numpy

In [70]:
a=np.array([1],dtype=np.long)
b=torch.from_numpy(a)
print(b.dtype)

torch.int64


In [183]:
# catenate in dimentions
a=torch.ones([2,1,1])
b=torch.ones([2,1,1])
c=torch.cat((a,b),dim=2)
c.shape

torch.Size([2, 1, 2])

In [6]:
a=torch.arange(3)
a.dtype

torch.int64

In [11]:
a.unsqueeze(0)

tensor([[0, 1, 2]])

In [15]:
b=torch.ones(3,3)
c=a.expand_as(b)
c

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

### dimensions

In [32]:
a=torch.arange(12).reshape(3,4)

In [34]:
a.shape

torch.Size([3, 4])

In [37]:
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [36]:
a.sum(1).shape

torch.Size([3])

In [38]:
a.sum(1)

tensor([ 6, 22, 38])

## datatype

In [16]:
torch.ones(3,3).dtype

torch.float32

In [19]:
torch.ones(3,3,dtype=torch.long).dtype

torch.int64

In [23]:
np.ones((3,3)).dtype

dtype('float64')

In [24]:
torch.from_numpy(np.ones((3,3))).dtype

torch.float64

In [29]:
torch.from_numpy(np.ones((3,3),dtype=np.int64)).dtype

torch.int64

In [31]:
torch.from_numpy(np.ones((3,3)).astype(np.int32)).dtype

torch.int32

### scatter & gather

In [4]:
# scatter, 把N-1维的数据散布到N维数据中
o=torch.zeros(3,3)

In [27]:
i=torch.ones(3,3)

i3=torch.arange(9).view(3,3)+1.0

In [28]:
i

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
i2

tensor([[1, 1, 1]])

In [30]:
i3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
index=torch.tensor([[1,1,0]])

In [35]:
index2=torch.tensor([[1,1,0],[1,1,0]])

In [32]:
o.scatter(0,index,i)

tensor([[0., 0., 1.],
        [1., 1., 0.],
        [0., 0., 0.]])

In [40]:
i2=torch.tensor([[1,1,1]])
index=torch.tensor([[1,1,0]])
o.scatter(0,index,i2.float())

tensor([[0., 0., 1.],
        [1., 1., 0.],
        [0., 0., 0.]])

In [42]:
i2=torch.tensor([[1,1,1]])
index=torch.tensor([1,1,0]).unsqueeze(1)
o.scatter(1,index,i)

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

In [34]:
o.scatter(0,index,i3.float())

tensor([[0., 0., 3.],
        [1., 2., 0.],
        [0., 0., 0.]])

In [36]:
o.scatter(0,index2,i3.float())

tensor([[0., 0., 6.],
        [4., 5., 0.],
        [0., 0., 0.]])

In [43]:
index3=torch.tensor([[1,1,0],[2,2,1]])
o2=o.scatter(0,index3,i3.float())
o2

tensor([[0., 0., 3.],
        [1., 2., 6.],
        [4., 5., 0.]])

In [47]:
# gather
torch.gather(o2,0,torch.tensor([[1,1,0]]))

tensor([[1., 2., 3.]])

In [53]:
a = torch.ones(3,2,2)
mask = torch.zeros(3,2)

In [54]:
a.masked_fill(mask.unsqueeze(1)==0, 2)

tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])

In [64]:
z=torch.tensor([1])

In [67]:
z.data.item()

1

In [62]:
torch.get_default_dtype()

torch.float32

In [58]:
help(torch.arange)

Help on built-in function arange:

arange(...)
    arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a 1-D tensor of size :math:`\left\lfloor \frac{\text{end} - \text{start}}{\text{step}} \right\rfloor`
    with values from the interval ``[start, end)`` taken with common difference
    :attr:`step` beginning from `start`.
    
    Note that non-integer :attr:`step` is subject to floating point rounding errors when
    comparing against :attr:`end`; to avoid inconsistency, we advise adding a small epsilon to :attr:`end`
    in such cases.
    
    .. math::
        \text{out}_{{i+1}} = \text{out}_{i} + \text{step}
    
    Args:
        start (Number): the starting value for the set of points. Default: ``0``.
        end (Number): the ending value for the set of points
        step (Number): the gap between each pair of adjacent points. Default: ``1``.
        out (Tensor, optional): the output tensor
  

## Linear Module

### And Gate

In [33]:
def sign(x):
    if x>0:
        return 1
    else:
        return 0

In [31]:
neu_and=nn.Linear(2,1)
neu_and.weight=nn.Parameter(torch.Tensor([[1,1]]))
neu_and.bias=nn.Parameter(torch.Tensor([-1.5]))

In [34]:
# 1 and 1
sign(neu_and(torch.Tensor([[1,1]])))

1

In [36]:
# 1 and 0
sign(neu_and(torch.Tensor([[1,0]])))

0

In [37]:
# 0 and 1
sign(neu_and(torch.Tensor([[0,1]])))

tensor([[-0.5000]], grad_fn=<AddmmBackward>)

In [38]:
# 0 and 0
sign(neu_and(torch.Tensor([[0,0]])))

0

In [2]:
linear3to2 = nn.Linear(3,2)

In [3]:
X = torch.ones(5,4,3)

In [4]:
y = linear3to2(X)

In [5]:
y.shape

torch.Size([5, 4, 2])

## weight Embedding

In [45]:
emb=nn.Embedding(5,2)
emb.weight

Parameter containing:
tensor([[-0.3816,  0.3944],
        [-0.6221, -0.4902],
        [ 0.1252,  0.4183],
        [ 1.0135, -0.5139],
        [ 0.1322, -0.7540]], requires_grad=True)

In [71]:
emb(torch.Tensor([1,3]).long())

tensor([[-0.6221, -0.4902],
        [ 1.0135, -0.5139]], grad_fn=<EmbeddingBackward>)

## RNN
RNN的目标是让隐含变量包含之前（含当前）的状态信息
$$
h_t=\tanh(W_{hh} h_{t-1}+W_{xh} x_t)
$$

### LSTM
为解决梯度消失或爆炸
$$
\hat{c}_t=\tanh(W_{hc} h_{t-1}+W_{xc} x_t) \\
c_t = c_{t-1}\cdot f_t + \hat{c}_t \cdot i_t \\
h_t = o_t \cdot \tanh(c_t)
$$

### GRU
$$
\hat{h}_t=tanh(W_{xh}X_t+r_t\cdot W_{hh}h_{t-1}) \\
h_t = z_t \cdot h_{t-1} + (1-z_t)\hat{h}_t
$$


In [131]:
gru = nn.GRU(
    input_size=1, 
    hidden_size=1,
    num_layers=1,
    bidirectional=False,
    dropout=0,
    batch_first=True)

In [132]:
gru.weight_hh_l0.data=torch.ones(3,1)

In [133]:
gru.weight_ih_l0.data=torch.ones(3,1)*2

In [134]:
weight = next(gru.parameters()).data


In [135]:
hid_shape = (gru.num_layers * 1, 2, gru.hidden_size)

In [140]:
init_hidden=weight.new(*hid_shape).zero_()

In [141]:
init_hidden

tensor([[[0.],
         [0.]]])

In [142]:
gru.weight_hh_l0.data

tensor([[1.],
        [1.],
        [1.]])

In [143]:
gru.weight_ih_l0.data

tensor([[2.],
        [2.],
        [2.]])

In [146]:
# init_hidden: num_layers * num_directions, batch_size, hidden_size
out,hidden=gru(torch.ones(2,5,1),init_hidden)
print(out)
print(hidden)

tensor([[[0.1709],
         [0.2952],
         [0.3908],
         [0.4671],
         [0.5295]],

        [[0.1709],
         [0.2952],
         [0.3908],
         [0.4671],
         [0.5295]]], grad_fn=<TransposeBackward0>)
tensor([[[0.5295],
         [0.5295]]], grad_fn=<StackBackward>)


In [149]:
out.size()

torch.Size([2, 5, 1])

In [151]:
forward_ = out[:, -1, :gru.hidden_size]
backward = out[:, 0, gru.hidden_size:]

In [153]:
forward_

tensor([[0.5295],
        [0.5295]], grad_fn=<SelectBackward>)

In [154]:
backward

tensor([], size=(2, 0), grad_fn=<SliceBackward>)

In [155]:
r=torch.cat((forward_, backward), dim=1)

In [156]:
r

tensor([[0.5295],
        [0.5295]], grad_fn=<CatBackward>)

In [4]:
# input_size – The number of expected features in the input x
# hidden_size – The number of features in the hidden state h
# num_layers – Number of recurrent laye
rnn = nn.LSTM(10, 20, 2)
input = torch.randn(5, 3, 10) # seq_size, batch_size, input_dim
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

In [3]:
output.shape # seq_size, batch, hidden_dim

torch.Size([5, 3, 20])

In [24]:
ot=output[-1,-1,:]
ot

tensor([ 0.0707,  0.0199,  0.0636, -0.0227,  0.1038, -0.1796, -0.0881, -0.0677,
         0.1000, -0.0347, -0.0276,  0.1323,  0.0640, -0.0565,  0.0018, -0.1523,
         0.0456, -0.0465,  0.1359,  0.0744], grad_fn=<SliceBackward>)

In [26]:
hn.shape # num_layers * num_directions, batch, hidden_size

torch.Size([2, 3, 20])

In [29]:
ht=hn[:,-1,:]
ht

tensor([[-0.1844, -0.1901, -0.1380, -0.0107,  0.0431, -0.0379,  0.0709,  0.0870,
          0.1797,  0.0604,  0.0771,  0.0704, -0.0285, -0.0497, -0.1527, -0.1410,
          0.0234,  0.0655,  0.1552, -0.1237],
        [ 0.0707,  0.0199,  0.0636, -0.0227,  0.1038, -0.1796, -0.0881, -0.0677,
          0.1000, -0.0347, -0.0276,  0.1323,  0.0640, -0.0565,  0.0018, -0.1523,
          0.0456, -0.0465,  0.1359,  0.0744]], grad_fn=<SliceBackward>)

In [6]:
cn.shape

torch.Size([2, 3, 20])

In [21]:
ct=cn[:,-1,:]
ct

tensor([[-0.3054, -0.3316, -0.3166, -0.0197,  0.0970, -0.0654,  0.1510,  0.1610,
          0.3429,  0.1051,  0.1813,  0.1241, -0.0626, -0.0984, -0.3553, -0.3140,
          0.0384,  0.1360,  0.3639, -0.2995],
        [ 0.1405,  0.0428,  0.1404, -0.0514,  0.2384, -0.3990, -0.1766, -0.1440,
          0.1891, -0.0784, -0.0606,  0.3589,  0.1054, -0.1066,  0.0034, -0.3195,
          0.0973, -0.0904,  0.2828,  0.1608]], grad_fn=<SliceBackward>)

In [17]:
ot*torch.tanh(ct)

tensor([ 2.5782e-02,  1.3208e-02, -2.9164e-02, -1.3137e-02,  1.3589e-01,
         2.5824e-02,  5.0664e-02,  6.7660e-02,  3.4473e-02,  5.9417e-03,
        -8.4059e-03,  2.2148e-02,  1.1468e-02,  2.2448e-02, -2.8409e-05,
         6.8456e-02, -5.8873e-03,  4.6585e-02,  3.9016e-03, -3.1660e-03],
       grad_fn=<MulBackward0>)

In [19]:
ht/ot

tensor([ 0.3828,  0.0644, -0.3041, -0.0889,  0.1787,  2.6366,  0.3040,  0.1431,
         0.5420,  0.4563, -0.1988,  2.0564,  0.5866,  0.2674, -0.2118,  0.6876,
        -0.7507,  0.0899,  9.5958, -3.7488], grad_fn=<DivBackward0>)


## Tricks 

### Weight Norm
seperate weight direction and magnitude
- weight magnitude: weight_g
- weight direction: weight_v

In [42]:
from torch.nn.utils.weight_norm import weight_norm

In [43]:
linear1 = nn.Linear(2,2)
weight_norm(linear1)

Linear(in_features=2, out_features=2, bias=True)

In [44]:
linear1._parameters

OrderedDict([('bias', Parameter containing:
              tensor([-0.2077,  0.1790], requires_grad=True)),
             ('weight_g', Parameter containing:
              tensor([[0.1948],
                      [0.8153]], requires_grad=True)),
             ('weight_v', Parameter containing:
              tensor([[0.1327, 0.1426],
                      [0.6380, 0.5076]], requires_grad=True))])

## Functional

In [158]:
s=torch.ones(2,2,1)

In [159]:
s

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [162]:
s_prob=nn.functional.softmax(s,dim=1)

In [163]:
s_prob.size()

torch.Size([2, 2, 1])

In [5]:
a=torch.ones(2,2,2)*2

In [6]:
a.pow(2)

tensor([[[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]]])

In [10]:
a= torch.ones(2,2,2)*2

In [11]:
b= torch.ones(2,2)*3

In [12]:
a*b

tensor([[[6., 6.],
         [6., 6.]],

        [[6., 6.],
         [6., 6.]]])

In [13]:
c=[a[0],a[1]]

In [14]:
c

[tensor([[2., 2.],
         [2., 2.]]), tensor([[2., 2.],
         [2., 2.]])]

In [15]:
d = torch.stack(c,dim=0)

In [16]:
d

tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])

In [2]:
a=torch.ones(5,3,4)

In [17]:
f=a.transpose(1,2)

In [18]:
f.shape

torch.Size([5, 4, 3])

In [5]:
b=torch.ones(5,4,3)

In [7]:
c=torch.bmm(a,b)

In [8]:
c.shape

torch.Size([5, 3, 3])

In [10]:
d=nn.functional.softmax(c,2)

In [15]:
e=torch.bmm(d,a)

In [19]:
a =torch.ones(3,2)

In [20]:
b = torch.ones(3,2)

In [21]:
torch.cat([a,b],dim=1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [79]:
pred = torch.Tensor([[0,0]])
ans = torch.Tensor([[1,1]])

In [96]:
pred = torch.Tensor([[3]])
ans = torch.Tensor([[1]])

In [ ]:
# Loss


In [97]:
nn.functional.binary_cross_entropy_with_logits(pred, ans, reduction='sum')

tensor(0.0486)

In [99]:
-np.log(1+np.exp(-3))

-0.048587351573741958

In [108]:
pred = torch.Tensor([[1,3,5]])

In [110]:
torch.argmax(pred,dim=1)

tensor([2])

In [ ]:
g

In [106]:
help(torch.argmax)

Help on function argmax in module torch.functional:

argmax(input, dim=None, keepdim=False)
    Returns the indices of the maximum values of a tensor across a dimension.
    
    This is the second value returned by :meth:`torch.max`. See its
    documentation for the exact semantics of this method.
    
    Args:
        input (Tensor): the input tensor
        dim (int): the dimension to reduce. If ``None``, the argmax of the
            flattened input is returned.
        keepdim (bool): whether the output tensors have :attr:`dim`
            retained or not. Ignored if ``dim=None``.
    
    Example::
    
        >>> a = torch.randn(4, 4)
        >>> a
        tensor([[ 1.3398,  0.2663, -0.2686,  0.2450],
                [-0.7401, -0.8805, -0.3402, -1.1936],
                [ 0.4907, -1.3948, -1.0691, -0.3132],
                [-1.6092,  0.5419, -0.2993,  0.3195]])
    
    
        >>> torch.argmax(a, dim=1)
        tensor([ 0,  2,  0,  1])



In [113]:
logits = torch.Tensor([[1,2,3],[2,3,1]])

In [114]:
logits2 = torch.max(logits, 1)[1].data # argmax

In [115]:
logits2

tensor([2, 1])

In [117]:
logits2.shape

torch.Size([2])

In [120]:
logits.argmax(dim=1,keepdim=True).shape

torch.Size([2, 1])