In [1]:
import torch

In [3]:
import torch.nn as nn

In [4]:
import torch.nn.functional

In [5]:
a=nn.Linear(2,3)

In [6]:
b=nn.Linear(3,1)

In [53]:
s = nn.Sequential(a,b)

In [54]:
for name, value in s.named_parameters():
    print(name)
    print(value)

0.weight
Parameter containing:
tensor([[-1.9272, -1.2925],
        [ 1.0217,  0.2621],
        [ 0.2712, -0.6385]], requires_grad=True)
0.bias
Parameter containing:
tensor([-2.9012,  1.9903, -0.2024], requires_grad=True)
1.weight
Parameter containing:
tensor([[ 5.0571, -2.2877, -1.6559]], requires_grad=True)
1.bias
Parameter containing:
tensor([-8.3193], requires_grad=True)


In [55]:
lr=0.1
params=[]
for name, value in s.named_parameters():
    if 'bias' in name:
        if '1' in name:
            params += [{'params':value, 'lr': 0 * lr, 'weight_decay': 0}]
        else:
            params += [{'params':value, 'lr': 2 * lr, 'weight_decay': 0}]
    else:
        if '1' in name:
            params += [{'params':value, 'lr': 10 * lr}]
        else:
            params += [{'params':value, 'lr': 1 * lr}]

In [56]:
params

[{'lr': 0.1, 'params': Parameter containing:
  tensor([[-1.9272, -1.2925],
          [ 1.0217,  0.2621],
          [ 0.2712, -0.6385]], requires_grad=True)},
 {'lr': 0.2, 'params': Parameter containing:
  tensor([-2.9012,  1.9903, -0.2024], requires_grad=True), 'weight_decay': 0},
 {'lr': 1.0, 'params': Parameter containing:
  tensor([[ 5.0571, -2.2877, -1.6559]], requires_grad=True)},
 {'lr': 0.0, 'params': Parameter containing:
  tensor([-8.3193], requires_grad=True), 'weight_decay': 0}]

In [57]:
optimizer = torch.optim.SGD(params, 0.5)

In [58]:
input = torch.ones(4,2)

In [59]:
output = s(input)

In [60]:
output.shape

torch.Size([4, 1])

In [61]:
loss = torch.sum(output)

In [62]:
loss.shape

torch.Size([])

In [63]:
for name, value in s.named_parameters():
    print(name)
    print(value)

0.weight
Parameter containing:
tensor([[-1.9272, -1.2925],
        [ 1.0217,  0.2621],
        [ 0.2712, -0.6385]], requires_grad=True)
0.bias
Parameter containing:
tensor([-2.9012,  1.9903, -0.2024], requires_grad=True)
1.weight
Parameter containing:
tensor([[ 5.0571, -2.2877, -1.6559]], requires_grad=True)
1.bias
Parameter containing:
tensor([-8.3193], requires_grad=True)


In [64]:
optimizer.zero_grad()

In [65]:
loss.backward()

In [66]:
for name, value in s.named_parameters():
    print(name)
    print(value)

0.weight
Parameter containing:
tensor([[-1.9272, -1.2925],
        [ 1.0217,  0.2621],
        [ 0.2712, -0.6385]], requires_grad=True)
0.bias
Parameter containing:
tensor([-2.9012,  1.9903, -0.2024], requires_grad=True)
1.weight
Parameter containing:
tensor([[ 5.0571, -2.2877, -1.6559]], requires_grad=True)
1.bias
Parameter containing:
tensor([-8.3193], requires_grad=True)


In [67]:
optimizer.step()

In [68]:
for name, value in s.named_parameters():
    print(name)
    print(value)

0.weight
Parameter containing:
tensor([[-3.9501, -3.3154],
        [ 1.9368,  1.1771],
        [ 0.9336,  0.0238]], requires_grad=True)
0.bias
Parameter containing:
tensor([-6.9469,  3.8204,  1.1223], requires_grad=True)
1.weight
Parameter containing:
tensor([[ 29.5410, -15.3838,   0.6230]], requires_grad=True)
1.bias
Parameter containing:
tensor([-8.3193], requires_grad=True)


In [73]:
class mynet(nn.Module):
    def __init__(self):
        super(mynet, self).__init__()
        self.feature = nn.Sequential(nn.Linear(2,3),nn.Linear(3,1))
        self.fc1 = nn.Linear(1,5)

In [74]:
mnet = mynet()

In [75]:
for name, value in mnet.named_parameters():
    print(name)
    print(value)

feature.0.weight
Parameter containing:
tensor([[ 0.2014, -0.5081],
        [-0.1404, -0.5360],
        [ 0.5596,  0.5818]], requires_grad=True)
feature.0.bias
Parameter containing:
tensor([ 0.5932, -0.5712,  0.5116], requires_grad=True)
feature.1.weight
Parameter containing:
tensor([[-0.5601, -0.5184,  0.0063]], requires_grad=True)
feature.1.bias
Parameter containing:
tensor([-0.2122], requires_grad=True)
fc1.weight
Parameter containing:
tensor([[-0.8672],
        [-0.2002],
        [-0.6201],
        [-0.9038],
        [ 0.1738]], requires_grad=True)
fc1.bias
Parameter containing:
tensor([ 0.7132, -0.7115, -0.4763, -0.9603, -0.5798], requires_grad=True)


In [79]:
mnet.fc1.weight.data=torch.ones(5,1)

In [80]:
mnet.fc1.weight.data

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [81]:
!ls data

ls: data: No such file or directory
